name: Go

on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: env PROJECT_VERSION=${GITHUB_REF/refs\/tags\//} make build-all release-body

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          release/p-Linux-x86_64
          release/p-Linux-i386
          release/p-Linux-armv5l
          release/p-Linux-armv6l
          release/p-Linux-armv7l
          release/p-Linux-armv8l
          release/p-Darwin-x86_64
          release/p-Darwin-i386
        body_path: RELEASE.md
